config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  resources :users, only: [:show]

  resources :restaurants, except: :index do
    resources :meals, only: %i[new create edit update destroy] do
      patch :move
    end
  end

  resources :meals, only: %i[index show] do
    resources :bookings, only: %i[new create]
    resources :favorites, only: %i[create]
    resources :reviews, only: %i[show new create]
  end

  resources :bookings, only: %i[index show destroy]

  resources :chatrooms, only: %i[index]

  resources :chatrooms, only: %i[show] do
    resources :messages, only: :create
  end

  namespace :my do
    resources :bookings, only: %i[index show edit update destroy]
  end

  resources :favorites, only: %i[index show update destroy]

  get '/badges', to: 'pages#badges'
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :meal

  validates :date, presence: true
  validates :number_people, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[show]
  before_action :set_meal, only: %i[new create]

  def index
    @bookings = Booking.where(user_id: current_user)
  end

  def show
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.meal = @meal
    @booking.user = current_user

    if @booking.save
      @chatroom = Chatroom.new(name: @booking.user, booking_id: @booking.id)
      @chatroom.save

      redirect_to booking_path(@booking)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_meal
    @meal = Meal.find(params[:meal_id])
  end

  def booking_params
    params.require(:booking).permit(:date, :number_people)
  end
end

app/controllers/my/bookings_controller.rb
class My::BookingsController < ApplicationController
  def index
    @meals = current_user.restaurant.meals
    @bookings = Booking.where(meal_id: @meals)
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to my_bookings_path, status: :see_other
  end
end

app/views/bookings/_booking.html.erb
<div class="card card-meal-list my-3 position-relative">
  <div class="card-image">
    <%= link_to booking_path(booking), class:"text-decoration-none text-reset" do %>
      <%= cl_image_tag booking.meal.photo.key, style:"border-radius: 10px; margin: 5px", alt: "meal", width: 90, height: 90, crop: :fill %>
    <% end %>
  </div>
    <div class="card-meal-infos">
      <h4 class="card-meal-name"><%= booking.meal.restaurant.name %> - <%= booking.meal.name %></h4>
      <small><i class="fa-solid fa-user-group" style="margin-bottom:10px;"></i> <%= booking.number_people %> personne(s)</small><br>
      <small><i class="fa-solid fa-clock"></i> <%= booking.date.strftime("%d/%m/%Y") %> à <%= booking.date.strftime("%H") %>h<%= booking.date.strftime("%M") %></small>
    </div>
</div>

app/views/bookings/new.html.erb
<div class="container mb-5">
  <div class="row">
    <div class="col-12">
      <h2 class="text-center my-3">Nouvelle réservation</h2>
      <div class="card-booking p-3 mb-3">
        <div class="card-booking-description">
          <h5>Détails</h5>
          <small><i class="fa-solid fa-utensils"></i> <%= @meal.name %> - <%= @meal.price %>€</small><br>
          <small><i class="fa-solid fa-location-dot"></i> <%= @meal.restaurant.name %> - <%= @meal.restaurant.address %></small>
        </div>
      </div>
      <div class="text-center">
        <%= simple_form_for [@meal, @booking] do |f| %>
          <div class="d-flex justify-content-center post">
            <%= f.input :date, html5: true %>
          </div>
          <div class="d-flex justify-content-center post">
            <%= f.input :number_people, label: "Nombre de personnes" %>
          </div>
          <%= f.button :submit, "Valider ma réservation", class: "btn btn-orange w-90 mt-3" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container mb-5">
  <div class="row">
    <div class="col-12">
      <h2 class="text-center my-3">Réservation n°<%= @booking.id %></h2>
      <div class="cards">
        <div class="card-booking p-3 mb-3">
          <div class="card-booking-description">
            <h5>
              Détails de la réservation
            </h5>
              <small><i class="fa-solid fa-clock"></i> <%= @booking.date.strftime("%d/%m/%Y") %> à <%= @booking.date.strftime("%H") %>h<%= @booking.date.strftime("%M") %></small><br>
              <small><i class="fa-solid fa-user-group"></i> <%= @booking.number_people %> personnes</small>
          </div>
        </div>
        <div class="card-booking-meal p-3 mb-3">
          <div class="card-booking-description">
            <h5>
              Restaurant
            </h5>
            <small><i class="fa-solid fa-location-arrow"></i> <%= @booking.meal.restaurant.name %></small><br>
            <small><i class="fa-solid fa-location-dot"></i> <%= @booking.meal.restaurant.address %></small><br>
            <small><i class="fa-solid fa-phone"></i> <%= @booking.meal.restaurant.phone %></small>
          </div>
        </div>
        <div class="card-booking-meal p-3 mb-3">
          <div class="card-booking-description">
            <h5>Plat réservé</h5>
            <%= cl_image_tag @booking.meal.photo.key, width: '100%', class: 'mb-3', style:"border-radius: 10px;" %>
            <p><%= @booking.meal.name %> - <%= @booking.meal.price %> €</p>
            <p><i class="fa-solid fa-tag"></i> <%= @booking.meal.category %></p>
            <p class="mb-0"><i class="fa-solid fa-circle-info"></i> <%= @booking.meal.description %></p>
          </div>
        </div>
      </div>
      <% if current_user.owner %>
        <%= link_to "Supprimer la réservation", my_booking_path(@booking), class: "btn btn-orange w-100", data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>
      <% end %>
    </div>
  </div>
</div>