config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  resources :users, only: [:show]

  resources :restaurants, except: :index do
    resources :meals, only: %i[new create edit update destroy] do
      patch :move
    end
  end

  resources :meals, only: %i[index show] do
    resources :bookings, only: %i[new create]
    resources :favorites, only: %i[create]
    resources :reviews, only: %i[show new create]
  end

  resources :bookings, only: %i[index show destroy]

  resources :chatrooms, only: %i[index]

  resources :chatrooms, only: %i[show] do
    resources :messages, only: :create
  end

  namespace :my do
    resources :bookings, only: %i[index show edit update destroy]
  end

  resources :favorites, only: %i[index show update destroy]

  get '/badges', to: 'pages#badges'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :favorites
  has_many :bookings
  has_one :restaurant, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :meals, through: :bookings

  validates :first_name, :last_name, :address, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  end

end

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 p-0">
      <div class="cards m-3 position-relative">
        <h2 class="text-center my-3">Profil</h2>
        <div style="margin-top:32px;">
          <div class="card-meal-show p-3">
            <h3>Bonjour <%= current_user.first_name %></h3>
            <p>Que souhaitez-vous faire?</p>
            <ul style="list-style-type:none;" class="p-0">
              <li><%= link_to "Changer de mot de passe", edit_user_registration_path, class:"text-reset" %></li>
              <li><%= link_to "Supprimer mon compte", destroy_user_session_path, class:"text-reset" %></li>
            </ul>
          </div>
          <div class="card-meal-show p-3 my-3">
            <table>
              <thead>
                <tr>
                  <th colspan="2"><h3>Vos stats</h3></th>
                </tr>
              </thead>
              <tbody>
              <tr>
                <td>Réservation(s)</td>
                <td><span style="font-size: larger;"><%= current_user.bookings.size.to_i %></span> &nbsp; <i class="fa-regular fa-calendar"></i></td>
              </tr>
              <tr>
                <td>"J'aime"</td>
                <td><span style="font-size:larger;"><%= current_user.favorites.where(like: true).count %></span> &nbsp; <i class="fa-solid fa-heart"></i></td>
              </tr>
              <tr>
                <td>"Super j'aime"</td>
                <td><span style="font-size:larger;"><%= current_user.favorites.where(superlike: true).count %></span> &nbsp; <i class="fa-solid fa-fire"></i></td>
              </tr>
              <tr>
                <td>"J'aime pas"</td>
                <td><span style="font-size:larger;"><%= current_user.favorites.where(like: false).count %></span> &nbsp; <i class="fa-solid fa-heart-crack"></i></td>
              </tr>
              <tr>
                <td>Plat(s) mangé(s)</td>
                <td><span style="font-size:larger;"><%= current_user.favorites.where(eaten: true).count %></span> &nbsp; <i class="fa-solid fa-cookie-bite"></i></td>
              </tr>
              <tr>
                <td>Restaurant(s) visité(s)</td>
                <td><span style="font-size:larger;"><%= current_user.meals.map(&:restaurant).uniq.count %></span> &nbsp; <i class="fa-solid fa-store"></i> </td>
              </tr>
              </tbody>
            </table>
          </div>
          <%= link_to "Voir mes badges", badges_path, class: "btn btn-orange w-100" %>
        </div>
      </div>
    </div>
  </div>