config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  resources :users, only: [:show]

  resources :restaurants, except: :index do
    resources :meals, only: %i[new create edit update destroy] do
      patch :move
    end
  end

  resources :meals, only: %i[index show] do
    resources :bookings, only: %i[new create]
    resources :favorites, only: %i[create]
    resources :reviews, only: %i[show new create]
  end

  resources :bookings, only: %i[index show destroy]

  resources :chatrooms, only: %i[index]

  resources :chatrooms, only: %i[show] do
    resources :messages, only: :create
  end

  namespace :my do
    resources :bookings, only: %i[index show edit update destroy]
  end

  resources :favorites, only: %i[index show update destroy]

  get '/badges', to: 'pages#badges'
end

app/views/shared/_button_eaten.html.erb
<%= simple_form_for favorite do |f| %>
  <% if favorite.eaten == false %>
    <%= f.input :eaten, as: :hidden, input_html: { value: true } %>
    <div >
      <%= button_tag type: 'submit', style: 'border:none; background:none;' do %>
        <i class="fa-solid fa-cookie cookie-icon" style="color:grey"></i>
      <% end %>
    </div>
  <% else %>
    <%= f.input :eaten, as: :hidden, input_html: { value: true } %>
    <div >
      <%= button_tag type: 'submit', style: 'border:none; background:none;' do %>
        <i class="fa-solid fa-cookie-bite cookie-icon"></i>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/shared/_button_superlike.html.erb
<%= simple_form_for favorite do |f| %>
  <% if favorite.superlike == true %>
    <%= f.input :superlike, as: :hidden, input_html: { value: false } %>
    <div >
      <%= button_tag type: 'submit', style: 'border:none; background:none;' do %>
        <i class="fa-solid fa-heart heart-icon"></i>
      <% end %>
    </div>
  <% else %>
    <%= f.input :superlike, as: :hidden, input_html: { value: true } %>
    <div>
      <%= button_tag type: 'submit', style: 'border:none; background:none;' do %>
        <i class="fa-regular fa-heart" style="color:grey"></i>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/shared/_card-meal-list.html.erb
<h1 class="text-center">Mes plats</h1>
<%= link_to 'Ajouter un plat'.html_safe, new_restaurant_meal_path(@restaurant), class: "btn btn-orange w-100"  %>
<% @restaurant.meals.each do |meal| %>
  <%= link_to meal_path(meal), class:"text-decoration-none text-reset" do %>
    <div class="card card-meal-list my-3">
      <div class="card-image">
        <%= cl_image_tag meal.photo.key, style:"border-radius: 10px; margin: 5px", alt: "meal", width: 90, height: 90, crop: :fill %>
      </div>
        <div class="card-meal-infos">
          <h3 class="card-meal-name"><%= meal.name %></h3>
          <p class="card-meal-description"><%= meal.description %></p>
          <div class="card-price-part">
            <div class="category">
              <p><%= meal.category %></p>
            </div>
            <div class="meal-price">
              <p><%= meal.price %>€</p>
            </div>
          </div>
        </div>
    </div>
  <% end %>
<% end %>

app/views/shared/_card_chats_list.html.erb
<% @chatrooms.each do |chatroom| %>
  <% if current_user.id == chatroom.booking.meal.restaurant.user_id %>
    <div class="card card-meal-list my-3 position-relative">
      <div class= "btn btn-chat-index position-absolute">
        <%= link_to chatroom_path(chatroom) do %>
          <i class="fa-regular fa-comment-dots" style="color:grey"></i>
        <% end %>
      </div>
      <div class="card-image">
        <%= link_to chatroom_path(chatroom), class:"text-decoration-none text-reset" do %>
          <%= cl_image_tag chatroom.booking.meal.photo.key, style:"border-radius: 10px; margin: 5px", alt: "meal", width: 90, height: 90, crop: :fill %>
        <% end %>
      </div>
      <div class="card-meal-infos">
        <h4 class="card-meal-name"> <%= chatroom.booking.user.first_name %> <%= chatroom.booking.user.last_name %></h4>
        <p class="card-chat-description">Le <%= chatroom.booking.date.strftime("%d/%m/%Y") %> - <%= chatroom.booking.number_people %> personne(s)</p>
        <div class="card-price-part">
          <div class="category">
            <p><%= chatroom.booking.meal.name %></p>
          </div>
        </div>
      </div>
    </div>
  <% elsif current_user.id == chatroom.booking.user_id %>
    <div class="card card-meal-list my-3 position-relative">
      <div class= "btn btn-chat-index position-absolute">
        <%= link_to chatroom_path(chatroom) do %>
          <i class="fa-regular fa-comment-dots" style="color:grey"></i>
        <% end %>
      </div>
      <div class="card-image">
        <%= link_to chatroom_path(chatroom), class:"text-decoration-none text-reset" do %>
          <%= cl_image_tag chatroom.booking.meal.photo.key, style:"border-radius: 10px; margin: 5px", alt: "meal", width: 90, height: 90, crop: :fill %>
        <% end %>
      </div>
      <div class="card-meal-infos">
        <h4 class="card-meal-name"> <%= chatroom.booking.meal.restaurant.user.first_name %> <%= chatroom.booking.meal.restaurant.user.last_name %></h4>
        <p class="card-chat-description">Le <%= chatroom.booking.date.strftime("%d/%m/%Y") %> - <%= chatroom.booking.meal.restaurant.name %></p>
        <div class="card-price-part">
          <div class="category">
            <p><%= chatroom.booking.meal.name %></p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/shared/_card_favorites_list.html.erb
<% @favorites.where(like: true).each do |favorite| %>
  <div class="card card-meal-list my-3 position-relative">
    <div class="d-flex position-absolute all-btns">
      <%= render "shared/button_eaten", favorite: favorite %>
      <%= render "shared/button_superlike", favorite: favorite %>
    </div>
    <div class="position-absolute btn-delete">
      <%= render "shared/button_unlike", favorite: favorite %>
    </div>
    <div class="card-image">
      <%= link_to favorite_path(favorite), class:"text-decoration-none text-reset" do %>
        <%= cl_image_tag favorite.meal.photo.key, style:"border-radius: 10px; margin: 5px", alt: "meal", width: 90, height: 90, crop: :fill %>
      <% end %>
    </div>
      <div class="card-meal-infos">
        <h4 class="card-meal-name"><%= favorite.meal.name %></h4>
        <p class="card-meal-description"><%= favorite.meal.description %></p>
        <div class="card-price-part">
          <div class="category">
            <p><%= favorite.meal.category %></p>
          </div>
          <div class="meal-price">
            <p style="font-size: larger;"><%= favorite.meal.price %>€</p>
          </div>
        </div>
      </div>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_icons_likes.html.erb
<div class="icon-position">
  <%# icons X %>
  <%= simple_form_for [meal, @favorite], data: { swipe_target: "dislikeForm" } do |f| %>
    <%= f.input :superlike, as: :hidden, input_html: { value: false } %>
    <%= f.input :like, as: :hidden, input_html: { value: false } %>
    <%=button_tag class:"icon" do %>
      <i class="fa-solid fa-circle-xmark icon-fav" style="color: #ff6464"></i>
    <% end %>
  <% end %>


  <%# icon superlike %>
  <%= simple_form_for [meal, @favorite], data: { swipe_target: "superlikeForm" } do |f| %>
    <%= f.input :superlike, as: :hidden, input_html: { value: true } %>
    <%= f.input :like, as: :hidden, input_html: { value: true } %>
    <%= button_tag class:"icon" do %>
      <i class="fa-solid fa-fire icon-fav" style="color: #ffbd67"></i>
    <% end %>
  <% end %>

  <%# icon like %>
  <%= simple_form_for [meal, @favorite], data: { swipe_target: "likeForm" } do |f| %>
    <%= f.input :superlike, as: :hidden, input_html: { value: false } %>
    <%= f.input :like, as: :hidden, input_html: { value: true } %>
    <%= button_tag class:"icon" do %>
      <i class="fa-solid fa-heart icon-fav" style="color: #5be7a9"></i>
    <% end %>
  <% end %>
</div>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_meal.html.erb
<%# TODO Partial meal : Name / Photo / Price / Rating %>
<div class="meal-img" style="width: 100%; aspect-ratio: 1/1;">
  <%= cl_image_tag meal.photo.key, class:"meal-show-img", alt: "food", width: 300, height: 300, crop: :fill, style: "border-radius: 10px;" %>
</div>
<div class="card-meal-show-text">
  <h2><%= meal.name %></h2>
  <p><%= meal.description %></p>
  <p style="font-size: 23px;"><%= meal.price %>€</p>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light fixed-bottom navbar-lewagon">
  <div class="container-fluid">
    <% if user_signed_in? %>
      <% if current_user.owner %>
        <div class="w-100">
          <ul class="nav">
            <li class="nav-item owner">
              <%= link_to restaurant_path(current_user.restaurant), class: "nav-link #{request.path.match?('/restaurants') ? 'colored' : ''}" do %>
                <i class="fa-solid fa-store"></i>
                <small>Restaurant</small>
              <% end %>
            </li>
            <li class="nav-item owner">
              <%= link_to my_bookings_path, class: "nav-link #{request.path.match?('/my/bookings') ? 'colored' : ''}" do %>
                <i class="fa-solid fa-calendar"></i>
                <small>Réservations</small>
              <% end %>
            </li>
            <li class="nav-item owner">
              <%= link_to chatrooms_path, class: "nav-link #{request.path.match?('/chatrooms') ? 'colored' : ''}" do %>
                <i class="fa-solid fa-comments"></i>
                <small>Messagerie</small>
              <% end %>
            </li>
            <li class="nav-item owner">
              <%= link_to user_path(current_user), class: "nav-link #{request.path.match?('/users') ? 'colored' : ''}" do %>
                <i class="fa-solid fa-user"></i>
                <small>Mon profil</small>
              <% end %>
            </li>
          </ul>
        </div>
      <% else %>
        <div class="w-100">
          <ul class="nav">
            <li class="nav-item user">
              <%= link_to bookings_path, class: "nav-link #{request.path.match?(/.?\/bookings.?/) ? 'colored' : ''}" do %>
                  <i class="fa-solid fa-calendar"></i>
                  <small>Réservations</small>
              <% end %>
            </li>
            <li class="nav-item user">
              <%= link_to favorites_path, class: "nav-link #{request.path.match?(favorites_path) || request.path.include?('reviews') ? 'colored' : ''}" do %>
                <i class="fa-solid fa-heart"></i>
                <small>Favoris</small>
              <% end %>
            </li>
            <li class="nav-item user">
              <%= link_to meals_path, class: "nav-link #{request.path.include?('meals') && request.path.exclude?('bookings') && request.path.exclude?('reviews')? 'colored' : ''}" do %>
                <i class="fa-solid fa-burger"></i>
                <small>Découvrir</small>
              <% end %>
            </li>
            <li class="nav-item user">
            <%= link_to chatrooms_path, class: "nav-link #{request.path.match?(chatrooms_path) ? 'colored' : ''}" do %>
                <i class="fa-solid fa-comments"></i>
                <small>Messagerie</small>
              <% end %>
            </li>
            <li class="nav-item user">
            <%= link_to user_path(current_user), class: "nav-link #{request.path.match?('users/') || request.path.include?('badges') ? 'colored' : ''}" do %>
                <i class="fa-solid fa-user"></i>
                <small>Profil</small>
              <% end %>
            </li>
        </ul>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_restaurant.html.erb
<h1><%= restaurant.name %></h1>
<%= link_to  edit_restaurant_path(@restaurant) do%>
  <i class="fa-solid fa-pen-to-square" ></i>
<% end %>
<p><i class="fa-solid fa-shop"></i> <%= restaurant.address %></p>
<p><i class="fa-solid fa-phone"></i> <%= restaurant.phone %></p>

app/views/shared/_review.html.erb
<p><%= review.rating %><i class="fa-solid fa-star rate-icon"></i> - <%= review.content %></p>

app/views/shared/_review_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-8 offset-2">
      <div class="card-create p-3 shadow-none">
        <%= simple_form_for [@meal, @review] do |f| %>
          <%= f.input :rating, collection: Review::AUTHORIZED_RATINGS, label: "Note du plat ⭐️"  %>
          <%= f.input :content, label: "Donner un avis", placeholder: 'Très bon plat 👍', as: :text, input_html: {rows: 5, cols: 10} %>
          <%= f.submit "Valider", class: 'btn btn-orange w-100' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_top-navbar.html.erb
<nav class="navbar bg-white top-navbar fixed-top">
  <div class="d-flex w-100 justify-content-between px-3 align-items-center">
    <div class="logo">
      <%= image_tag "logo-swipeat.svg", width:"120", height:"35" %>
    </div>
    <div class="logout">
      <%= link_to '<i class="fa-solid fa-power-off"></i>'.html_safe, destroy_user_session_path , data: {turbo_method: :delete} %>
    </div>
  </div>
</nav>