config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  resources :users, only: [:show]

  resources :restaurants, except: :index do
    resources :meals, only: %i[new create edit update destroy] do
      patch :move
    end
  end

  resources :meals, only: %i[index show] do
    resources :bookings, only: %i[new create]
    resources :favorites, only: %i[create]
    resources :reviews, only: %i[show new create]
  end

  resources :bookings, only: %i[index show destroy]

  resources :chatrooms, only: %i[index]

  resources :chatrooms, only: %i[show] do
    resources :messages, only: :create
  end

  namespace :my do
    resources :bookings, only: %i[index show edit update destroy]
  end

  resources :favorites, only: %i[index show update destroy]

  get '/badges', to: 'pages#badges'
end

app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :restaurant
  acts_as_list

  CATEGORY = ["Brasserie", "Italien", "Africain", "Indien", "Libanais", "Turque", "Asiatique",
    "Coréen", "Salade", "Poke", "Végétarien", "Mexicain", "Fast food", "Chinois"]

  has_many :favorites, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
  has_many :reviews, dependent: :destroy

  validates :name, presence: true, length: { minimum: 2 }
  validates :description, presence: true, length: { maximum: 500 }

  validates :price, presence: true
  validates :photo, presence: true
  validates :category, presence: true
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :set_meal, only: %i[show edit update destroy]
  before_action :set_restaurant, only: %i[new create edit update destroy]

  def index
    @meals = Meal.all.shuffle - current_user.favorites.map { |item| item.meal }

    if params[:meal].to_i && params[:meal].to_i != 0
      @meals << Meal.find(params[:meal].to_i)
    elsif params[:query].present?
      categories = params[:query][:category].reject{ |category| category.blank? }
      @meals = Meal.where(category: categories)
    end
    @favorite = Favorite.new

  end

  def show
    @restaurant = @meal.restaurant
    @favorite = Favorite.new
    @review = Review.where(meal_id: @meal)
  end

  def new
    @meal = Meal.new
  end

  def create
    @meal = Meal.new(meal_params)
    @meal.restaurant = @restaurant
    if @meal.save
      redirect_to meal_path(@meal)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @meal.restaurant = @restaurant
    @meal.update(meal_params)
    redirect_to meal_path(@meal)
  end

  def destroy
    @meal.destroy
    redirect_to restaurant_path(@restaurant), status: :see_other
  end

  def move
    @meal = Meal.find(params[:meal_id])
    @meal.insert_at(params[:position].to_i)
    head :ok
  end

  private

  def meal_params
    params.require(:meal).permit(:name, :category, :description, :price, :photo)
  end

  def set_meal
    @meal = Meal.find(params[:id])
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/views/meals/edit.html.erb
<div class="container mb-5">
  <div class="row">
    <div class="col-12">
      <h2 class="text-center my-3">Modifier un plat 👨🏻‍🍳</h2>
      <%= render "shared/meal_form", meal: @meal%>
    </div>
  </div>
</div>

app/views/meals/index.html.erb
<div class="container">
    <div class="search">
      <%= simple_form_for(:query, url: meals_path, method: :get) do |f| %>
        <div class="d-flex" data-filter-target="button" style="padding-top: 2vh">
          <div class="boxes">
            <%= f.input :category, collection: Meal::CATEGORY, input_html: {multiple: true, data: {controller: "filter", filter_options_value: {tags: true}}, value: @categories}, label: false %>
          </div>
          <div style="margin-left: 1vh; margin-top: 1vh;">
            <%= submit_tag "Filtrer", class: "btn btn-orange" %>
          </div>
        </div>
      <% end %>
    </div>
  <div class="tinder" data-controller="swipe">
    <div class="tinder--cards">
      <% @meals.each do |meal| %>
        <div class="tinder--card" data-swipe-target="swipeCard">
          <div class="bg-gradient-image" style="background-image: linear-gradient(180deg, rgba(255,255,255,0) 0%, rgba(255,255,255,0) 80%, rgba(255,255,255,1) 100%), url(<%= cl_image_path meal.photo.key, alt: "food", crop: :fill %>);">
          <div class="meal-card-rate"><% rate = meal.reviews.map(&:rating).sum / meal.reviews.size.to_f %>
            <% if rate = 0 %>
              <h2><%= "" %></h2>
            <% else %>
              <h2><%= "#{rate}⭐️" %></h2>
            <% end %></div>
          </div>
          <div class="info-content">
            <%= link_to meal_path(meal), class: "text-decoration-none text-reset" do %>
              <i class="fa-solid fa-circle-info"></i>
            <% end %>
            <div class="info-content-text">
              <h3><%= meal.name %></h3>
              <p style="font-size: 23px;"><%= meal.price %>€</p>
            </div>
          </div>
            <%= render "shared/icons_likes", meal: meal, favorite: @favorite %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/meals/new.html.erb
<div class="container mb-5">
  <div class="row">
    <div class="col-12">
      <h2 class="text-center my-3">Ajouter un plat 👨🏻‍🍳</h2>
      <%= render "shared/meal_form", meal: @meal%>
    </div>
  </div>
</div>

app/views/meals/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 p-0">
      <% if @restaurant.user_id == current_user.id %>
          <div class="cards m-3">
            <div class="card-meal-show p-3 mb-3">
              <%= render "shared/meal", meal: @meal%>
              <div class="btn d-flex ">
                <div class="meal-show-button">
                  <%= link_to edit_restaurant_meal_path(@restaurant, @meal) do %>
                    <button class="btn btn-orange">Modifier</button>
                  <% end %>
                </div>
                <div class="meal-show-button">
                  <%= link_to restaurant_meal_path(@restaurant, @meal), data: {turbo_method: :delete, turbo_confirm: "Êtes vous sûr?"} do %>
                    <button class="btn btn-orange">Supprimer</button>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
      <% else %>
        <div class="cards m-3">
          <div class="card-meal-show p-3 mb-3" style="min-height: 80vh">
            <%= render "shared/meal", meal: @meal%>

            <div class="d-flex justify-content-center flex-column">
              <%= render "shared/icons_likes", meal: @meal, favorite: @favorite %>
              <div class="meal-show-button">
                <%= link_to meals_path(meal: @meal) do %>
                  <button class="btn btn-orange">Retour</button>
                <% end %>
              </div>
            </div>
          </div>
        </div>

        <div class="cards m-3">
          <div class="card-meal-show p-3 m-3">
            <div class="d-flex" style="justify-content: space-between;">
              <h2>Avis</h2>
              <% rate = @meal.reviews.map(&:rating).sum / @meal.reviews.size.to_f %>
              <% if rate.nan? %>
                <h2><%= "-" %></h2>
              <% else %>
                <h2 style="display: flex; justify-content:flex-start;"><%= rate.round(2) %>&nbsp;<i class="fa-solid fa-star rate-icon"></i></h2>
              <% end %>
            </div>
          <% @meal.reviews.each do |review|%>
            <%= render "shared/review", review: review %>
          <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>